# Generated by Django 2.2 on 2020-03-16 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARTICLES', '0002_auto_20200316_0239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstractjphiv',
            old_name='author',
            new_name='authors',
        ),
    ]
