# Generated by Django 2.2 on 2020-03-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARTICLES', '0004_anotatedjphiv_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractjphiv',
            name='DOI',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='abstractjphiv',
            name='doctype',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='abstractjphiv',
            name='sumber',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='abstractjphiv',
            name='volume',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
