# Generated by Django 2.2 on 2020-03-17 23:47

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('ARTICLES', '0005_auto_20200317_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractjphiv',
            name='authors',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
