# Generated by Django 2.2 on 2020-03-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARTICLES', '0006_auto_20200317_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotatedjphiv',
            name='DOI',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='anotatedjphiv',
            name='doctype',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='anotatedjphiv',
            name='sumber',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='anotatedjphiv',
            name='volume',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
