# Generated by Django 2.2 on 2020-03-19 15:17

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('ARTICLES', '0007_auto_20200318_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anotatedjphiv',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='abstractjphiv',
            name='visit_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anotatedjphiv',
            name='Author',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='+', through='ARTICLES.TaggedAuthor', to='ARTICLES.Author', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='anotatedjphiv',
            name='visit_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='abstractjphiv',
            name='authors',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='ARTICLES.TaggedAuthor', to='ARTICLES.Author', verbose_name='Tags'),
        ),
    ]
