# Generated by Django 2.2 on 2020-03-19 15:24

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('ARTICLES', '0008_auto_20200319_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taggedauthor',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Author'},
        ),
        migrations.AlterField(
            model_name='abstractjphiv',
            name='authors',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='ARTICLES.TaggedAuthor', to='ARTICLES.Author', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='anotatedjphiv',
            name='Author',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='+', through='ARTICLES.TaggedAuthor', to='ARTICLES.Author', verbose_name='Author'),
        ),
    ]
