# Generated by Django 2.2 on 2020-03-19 15:27

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('ARTICLES', '0009_auto_20200319_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractjphiv',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='abstractjphiv',
            name='authors',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='abstracts', through='ARTICLES.TaggedAuthor', to='ARTICLES.Author', verbose_name='Author'),
        ),
    ]
