# Generated by Django 2.2 on 2020-03-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARTICLES', '0010_auto_20200319_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstractjphiv',
            old_name='DOI',
            new_name='DOI_URL',
        ),
        migrations.RenameField(
            model_name='anotatedjphiv',
            old_name='DOI',
            new_name='DOI_URL',
        ),
        migrations.AddField(
            model_name='abstractjphiv',
            name='DOI_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='anotatedjphiv',
            name='DOI_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
