# Generated by Django 2.2 on 2020-03-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARTICLES', '0011_auto_20200319_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractjphiv',
            name='download',
            field=models.FileField(blank=True, upload_to='abstract/'),
        ),
        migrations.AlterField(
            model_name='anotatedjphiv',
            name='download',
            field=models.FileField(blank=True, upload_to='anotated/'),
        ),
    ]
