# Generated by Django 2.2 on 2020-03-27 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARTICLES', '0013_auto_20200326_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggedauthor',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles_taggedauthor_items', to='ARTICLES.Author'),
        ),
    ]
