# Generated by Django 2.2 on 2020-03-31 11:36

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ARTICLES', '0014_auto_20200327_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagAnotated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Annotated Tags',
                'verbose_name_plural': 'Annotated Tags',
            },
        ),
        migrations.CreateModel(
            name='TaggedAnnotated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_taggedannotated_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles_taggedannotated_items', to='ARTICLES.TagAnotated')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Author',
            },
        ),
        migrations.AlterField(
            model_name='anotatedjphiv',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', related_name='tagannotated', through='ARTICLES.TaggedAnnotated', to='ARTICLES.TagAnotated', verbose_name='Annotated Tags'),
        ),
    ]
