# Generated by Django 2.2 on 2020-07-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARTICLES', '0002_auto_20200615_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='Kategori',
            field=models.CharField(choices=[('epidemiologi', 'epidemiologi'), ('biomedis', 'biomedis'), ('ekonomi-kesehatan', 'ekonomi-kesehatan'), ('studi-kebijakan', 'studi-kebijakan'), ('sosial-perilaku', 'sosial-perilaku')], max_length=20),
        ),
    ]
